
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 22 22:05:49 CST 2025
//----------------------------------------------------

package act4;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 30;
  public static final int FUNCTION = 7;
  public static final int LBRACKET = 54;
  public static final int MULT = 47;
  public static final int CONST = 10;
  public static final int GE = 39;
  public static final int LPAREN = 50;
  public static final int COMMENT_BLOCK = 63;
  public static final int MINUS = 46;
  public static final int FOR = 6;
  public static final int DELETE = 25;
  public static final int RPAREN = 51;
  public static final int INSTANCEOF = 24;
  public static final int BOOLEAN_LITERAL = 31;
  public static final int SEMICOLON = 56;
  public static final int NOT = 44;
  public static final int AND = 42;
  public static final int LT = 40;
  public static final int TYPEOF = 23;
  public static final int OR = 43;
  public static final int IN = 26;
  public static final int COMMA = 57;
  public static final int THROW = 22;
  public static final int CLASS = 13;
  public static final int DIV = 48;
  public static final int BIGINT = 33;
  public static final int PLUS = 45;
  public static final int ASSIGN = 49;
  public static final int NULL_LITERAL = 32;
  public static final int IF = 3;
  public static final int THIS = 12;
  public static final int DOT = 58;
  public static final int LE = 38;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int RBRACKET = 55;
  public static final int SUPER = 15;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int EXPORT = 17;
  public static final int TRY = 19;
  public static final int NUMBER = 29;
  public static final int STRICT_EQ = 34;
  public static final int VOID = 27;
  public static final int EQ = 36;
  public static final int FINALLY = 21;
  public static final int ERROR = 64;
  public static final int IMPORT = 16;
  public static final int COLON = 60;
  public static final int LBRACE = 52;
  public static final int ELSE = 4;
  public static final int WHILE = 5;
  public static final int STRICT_NE = 35;
  public static final int DEFAULT = 18;
  public static final int LET = 9;
  public static final int RBRACE = 53;
  public static final int NE = 37;
  public static final int EXTENDS = 14;
  public static final int QUESTION = 59;
  public static final int SYMBOL = 2;
  public static final int COMMENT_LINE = 62;
  public static final int GT = 41;
  public static final int VAR = 28;
  public static final int IDENTIFIER = 61;
  public static final int CATCH = 20;
}

