
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 02 19:28:33 CST 2025
//----------------------------------------------------

package act4;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 34;
  public static final int FUNCTION = 7;
  public static final int LBRACKET = 58;
  public static final int MULT = 51;
  public static final int CONST = 10;
  public static final int GE = 43;
  public static final int LPAREN = 54;
  public static final int COMMENT_BLOCK = 67;
  public static final int MINUS = 50;
  public static final int FOR = 6;
  public static final int DELETE = 25;
  public static final int RPAREN = 55;
  public static final int INSTANCEOF = 24;
  public static final int STATIC = 29;
  public static final int BOOLEAN_LITERAL = 35;
  public static final int SEMICOLON = 60;
  public static final int NOT = 48;
  public static final int AND = 46;
  public static final int LT = 44;
  public static final int TYPEOF = 23;
  public static final int OR = 47;
  public static final int IN = 26;
  public static final int COMMA = 61;
  public static final int THROW = 22;
  public static final int CLASS = 13;
  public static final int DIV = 52;
  public static final int BIGINT = 37;
  public static final int PLUS = 49;
  public static final int ASSIGN = 53;
  public static final int NULL_LITERAL = 36;
  public static final int IF = 3;
  public static final int THIS = 12;
  public static final int DOT = 62;
  public static final int LE = 42;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int RBRACKET = 59;
  public static final int SUPER = 15;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int EXPORT = 17;
  public static final int TRY = 19;
  public static final int NUMBER = 33;
  public static final int STRICT_EQ = 38;
  public static final int VOID = 27;
  public static final int EQ = 40;
  public static final int FINALLY = 21;
  public static final int ERROR = 68;
  public static final int IMPORT = 16;
  public static final int COLON = 64;
  public static final int AWAIT = 31;
  public static final int LBRACE = 56;
  public static final int ELSE = 4;
  public static final int WHILE = 5;
  public static final int STRICT_NE = 39;
  public static final int DEFAULT = 18;
  public static final int LET = 9;
  public static final int CONSTRUCTOR = 32;
  public static final int RBRACE = 57;
  public static final int NE = 41;
  public static final int EXTENDS = 14;
  public static final int ASYNC = 30;
  public static final int QUESTION = 63;
  public static final int SYMBOL = 2;
  public static final int COMMENT_LINE = 66;
  public static final int GT = 45;
  public static final int VAR = 28;
  public static final int IDENTIFIER = 65;
  public static final int CATCH = 20;
}

